### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by sunny-g** [gliese-technology/mylar#7]
I'm wanting to incorporate Mylar into my app and am deciding between this package-based Mylar implementation (last updated in January) and [this](https://github.com/strikeout/mylar) not-package-based implementation last updated in November 2014. 

Given relative lack of open issues, I'm curious if this project is still being maintained and what else is on the roadmap (aside from the open issue of creating git subtrees from existing Meteor packages). I'd love to help in any way I can.

**Comment by bcohn12** [comment]
Likewise, I'd also like to use this package but want to make sure it's
maintained. Thanks so much

**Comment by ramijarrar** [comment]
We suspended development a few months ago because of issues with the original framework (included in the paper) that are a bottleneck on quality. We have plans for a new implementation based purely on the paper, but cannot reveal any details just yet.

In the meantime, you can still use this package for experimental/prototype work and while we will not be doing any more development, we are always happy to accept patches or answer any questions you may have.

**Comment by bcohn12** [comment]
Great! Thanks so much and good luck with the refactoring!

**Comment by sunny-g** [comment]
@ramijarrar that's great to hear! I still have a few questions:

1. The paper mentions that original implementation is being used in production at MIT and in a medical application, so I'd assume that (aside from a 3rd-party security audit), it's production-ready. Where does this project diverge from the original? 

2. Can you share any of the bottlenecks you've found that you're working to fix? It'd be nice to know what to look out for to start making meaningful contributions.

3. Will the interface of the rewrite stay the same as this project's, or should I expect a rewrite in the future?

Thanks again for the work y'all have done!

**Comment by LDubya** [comment]
If you're willing to accept patches, then I'd second #2. Show us what the bottlenecks were and maybe we can provide some patches.

**Comment by ramijarrar** [comment]
@sunny-g 

1. If you read more closely (pg. 12) you will see that it actually says the two applications you mention "plan to start using Mylar in the near future" (which is unlikely now considering the inactivity of the project)

2. While there are specific issues with the framework that you can attempt to fix or at least watch out for such as incomplete functionality (e.g Principal.remove_access) or the outdated browser extension for active attacker protection, when I talk about a "bottleneck on quality" I am actually referring to deeper rooted problems with the design (e.g the mechanism for encrypting data replaces chunks of the core mongo and ddp packages to intercept traffic through the collection methods) that make the codebase unreliable and must be addressed at a much lower level.

3. It will follow the API specified in the paper (see Figure 2) and as such will be significantly different to the current interface.

**Comment by yaserjarrar** [comment]
To clarify further: the paper (http://css.csail.mit.edu/mylar/mylar.pdf) mentions porting 6 applications to Mylar (including kChat). As Rami mentioned above ^ it is unclear whether the two 'production' apps: the homework app at MIT & the medical application - were ever actually ported to Mylar as the paper simply states that they "plan to start using Mylar in production in the near future".

Fundamentally the problem is that the codebase we ported didn't actually implement the API as described in the paper. The missing functionality - such as Principal.remove_access didn't hinder something like a chat application from functioning but would be a complete roadblock in other cases. 

We would be happy to accept patches/updates to add missing/broken functionality however you are still left with the fact that the design/architecture has been implemented poorly or perhaps hurriedly - and this leads us to believe that our efforts (and yours) would be much better directed at a re-implementation.

Essentially we would advise against attempting to utilise this in production at this stage.

**Comment by sunny-g** [comment]
@ramijarrar @yaserjarrar Cool, when I meant production, I was referencing what they  mentioned on their [website](https://css.csail.mit.edu/mylar/), which, granted, says the medical app is "under IRB approval and in alpha deployment".

Incomplete functionality and the outdated browser extension (which I can't seem to find) are definitely issues that constitute a bottleneck on quality, as does the fact that it only currently works by inserting Mylar code into existing Meteor packages. Though my main interest in this package is the easy-of-use in encrypting data client-side more than searching over encrypted data or secret sharing, I'd love to contribute to the rewrite in whatever way I can.

**Comment by yaserjarrar** [comment]
Well I think there are easier (or at least, less incomplete) ways to decrypt data client-side (off the top of my head the cryptoJS package & collection hooks should do the trick).

Perhaps something like this: https://medium.com/meteor-js/client-side-aes-encryption-with-meteor-3be8d645fc12

Once you implement the pattern you can easily abstract it such that all data is encrypted client side by default (see above link). The clever/unique thing about Mylar really is Raluca/Nickolai's work on Multi-key searchable encryption (i.e. http://eprint.iacr.org/2013/508.pdf) which is crucial to the Mylar security model. 

We will post an update here about any rewrite plans as soon as they are finalised from our end.

**Comment by TDSFugal** [comment]
Excellent discussion about an intriguing technology.  There are so many use cases.

How would the server-side re-write be accomplished programmatically?  Would this Meteor-variant be supported by Meteor, or would it be a diverging branch?  And if Meteor supports it, would the maintenance be done in-house at Meteor or by a third party?

**Comment by sunny-g** [comment]
@yaserjarrar Thank you for the link! That's exactly what I was looking for but couldn't find before I stumbled upon Mylar. And I completely agree that Mylar's ingenuity lies in search over encrypted text, not just easy client-side encryption. Thanks again!

**Comment by yaserjarrar** [comment]
@TDSFugal The whole point of this package was to avoid being a diverging branch of Meteor (i.e. like the strikeout implementation). It still "replaces chunks of the core mongo and ddp packages" deeper in the design and a rewrite would avoid doing even that (it may even be framework agnostic).
